/* Part catalogue: names, systems, regions, descriptions and functions.
   Geometry for each key lives in model_bones.js / model_soft.js (A.BUILD[key]). */
window.ANATOMY = window.ANATOMY || {};
(function (A) {
  'use strict';
  A.SYSTEMS = {
    skeleton:    { label: 'Skeleton',    color: '#e6d9bd', icon: 'bone' },
    muscles:     { label: 'Muscles',     color: '#c1493f', icon: 'muscle' },
    organs:      { label: 'Organs',      color: '#e29a82', icon: 'organ' },
    circulatory: { label: 'Circulatory', color: '#e0383d', icon: 'heart' },
    nervous:     { label: 'Nervous',     color: '#f1cf55', icon: 'nerve' }
  };
  A.REGIONS = ['Head', 'Neck', 'Spine', 'Thorax', 'Back', 'Abdomen', 'Pelvis', 'Upper limb', 'Lower limb'];
  A.TONES = { tendon: '#ece5d0', cartilage: '#c6dce3', artery: '#d12f34', vein: '#3b5bc9', pulm: '#6f59c8' };

  const BONE = '#eadfc6', MUS = '#a53a34', MUSD = '#8e3333';
  const D = (key, name, system, region, desc, fn, extra) => Object.assign({ key, name, system, region, desc, fn }, extra || {});
  const sided = { sided: true };

  A.PART_DEFS = [
    // ===================================================== SKELETON
    D('skull', 'Skull', 'skeleton', 'Head', 'The cranium and facial bones: eight cranial and fourteen facial bones joined by immovable sutures. Hollows hold the eyes, nose and inner ear.', 'Protects the brain and sense organs and anchors the muscles of the face and jaw.', { color: BONE, label: 3 }),
    D('mandible', 'Mandible', 'skeleton', 'Head', 'The lower jaw, the only movable bone of the skull. It hinges on the temporal bones at the temporomandibular joints.', 'Chews and speaks: holds the lower teeth and gives attachment to the chewing muscles.', { color: BONE }),
    D('teeth', 'Teeth', 'skeleton', 'Head', 'Thirty-two permanent teeth: incisors, canines, premolars and molars, each with an enamel crown and a root set in the jaw.', 'Bite, tear and grind food, the first step of digestion, and help shape speech sounds.', { color: '#f4efe0' }),
    D('hyoid', 'Hyoid bone', 'skeleton', 'Neck', 'A small U-shaped bone in the neck that is not joined to any other bone; it hangs from muscles and ligaments.', 'Supports the tongue and larynx and gives muscles of swallowing and speech a stable anchor.', { color: BONE }),
    D('cervical', 'Cervical spine', 'skeleton', 'Spine', 'Seven vertebrae (C1-C7) of the neck. C1 (atlas) carries the skull and C2 (axis) has a peg-like dens that it pivots on.', 'Supports the head and allows nodding and turning; protects the spinal cord and vertebral arteries.', { color: BONE }),
    D('thoracic', 'Thoracic spine', 'skeleton', 'Spine', 'Twelve vertebrae (T1-T12), each articulating with a pair of ribs; their long spinous processes point downward.', 'Forms the back of the rib cage and protects the spinal cord while allowing limited rotation.', { color: BONE }),
    D('lumbar', 'Lumbar spine', 'skeleton', 'Spine', 'Five large vertebrae (L1-L5) of the lower back with thick bodies and short blunt spinous processes.', 'Carries most of the body weight and allows bending and twisting of the trunk.', { color: BONE }),
    D('discs', 'Intervertebral discs', 'skeleton', 'Spine', 'Cushions of fibrocartilage between adjacent vertebrae: a tough outer ring around a gel-like core.', 'Absorb shock, spread loads and let the spine flex in every direction.', { color: '#cfe0e5' }),
    D('sacrum', 'Sacrum', 'skeleton', 'Pelvis', 'A triangular bone of five fused vertebrae wedged between the two hip bones, with paired openings for sacral nerves.', 'Transfers the weight of the trunk to the pelvis and forms the back wall of the birth canal.', { color: BONE }),
    D('coccyx', 'Coccyx', 'skeleton', 'Pelvis', 'The tailbone: three to five small fused vertebrae below the sacrum.', 'Attachment point for pelvic floor muscles and ligaments; takes weight when sitting leaning back.', { color: BONE }),
    D('sternum', 'Sternum', 'skeleton', 'Thorax', 'The breastbone: manubrium, body and xiphoid process. The collarbones and upper seven ribs attach to it.', 'Anchors the rib cage in front and protects the heart and great vessels.', { color: BONE, label: 2 }),
    D('ribs', 'Ribs', 'skeleton', 'Thorax', 'Twelve curved bones per side. Ribs 1-7 reach the sternum, 8-10 join the cartilage above, 11-12 are floating.', 'Form a protective cage for heart and lungs and lift and lower during breathing.', Object.assign({ color: BONE, label: 2 }, sided)),
    D('costal', 'Costal cartilage', 'skeleton', 'Thorax', 'Bars of hyaline cartilage that join the front ends of the upper ten ribs to the sternum or to each other.', 'Make the rib cage springy so it can expand for breathing and absorb blows.', Object.assign({ color: '#cfe3e8' }, sided)),
    D('clavicle', 'Clavicle', 'skeleton', 'Upper limb', 'The collarbone, a slim S-shaped bone running from the sternum to the acromion of the scapula.', 'Braces the shoulder away from the chest and transmits forces from the arm to the trunk.', Object.assign({ color: BONE, label: 1 }, sided)),
    D('scapula', 'Scapula', 'skeleton', 'Upper limb', 'The shoulder blade: a flat triangular bone with a spine, an acromion, a coracoid process and the glenoid socket.', 'Provides the socket of the shoulder joint and a gliding base for arm movement.', Object.assign({ color: BONE, label: 1 }, sided)),
    D('humerus', 'Humerus', 'skeleton', 'Upper limb', 'The long bone of the upper arm with a rounded head above and a hinge-shaped end at the elbow.', 'Lever for the arm; forms the shoulder and elbow joints and carries the radial nerve in its groove.', Object.assign({ color: BONE, label: 3 }, sided)),
    D('radius', 'Radius', 'skeleton', 'Upper limb', 'The forearm bone on the thumb side; its lower end is broad and forms most of the wrist joint.', 'Rotates around the ulna so the palm can turn up or down (supination and pronation).', Object.assign({ color: BONE }, sided)),
    D('ulna', 'Ulna', 'skeleton', 'Upper limb', 'The forearm bone on the little-finger side; its upper end, the olecranon, is the point of the elbow.', 'Forms the main hinge of the elbow with the humerus.', Object.assign({ color: BONE }, sided)),
    D('hand', 'Hand bones', 'skeleton', 'Upper limb', 'Twenty-seven bones: eight carpals in the wrist, five metacarpals in the palm and fourteen phalanges in the fingers and thumb.', 'Give the hand its precise grip and fine movement.', Object.assign({ color: BONE }, sided)),
    D('hip', 'Hip bone', 'skeleton', 'Pelvis', 'Each hip bone is the fusion of the ilium, ischium and pubis. It has a cup-shaped socket (acetabulum) for the femoral head.', 'Joins the trunk to the leg, carries the body weight and shelters the pelvic organs.', Object.assign({ color: BONE, label: 2 }, sided)),
    D('femur', 'Femur', 'skeleton', 'Lower limb', 'The thigh bone, the longest and strongest bone in the body. A ball-shaped head sits on an angled neck.', 'Carries body weight and is the lever for walking, running and jumping.', Object.assign({ color: BONE, label: 3 }, sided)),
    D('patella', 'Patella', 'skeleton', 'Lower limb', 'The kneecap, a triangular sesamoid bone embedded in the quadriceps tendon.', 'Protects the knee joint and increases the leverage of the thigh muscles.', Object.assign({ color: BONE }, sided)),
    D('tibia', 'Tibia', 'skeleton', 'Lower limb', 'The shinbone, the thick weight-bearing bone of the lower leg with a flat plateau above and the inner ankle bump below.', 'Transmits the weight from the knee to the ankle.', Object.assign({ color: BONE }, sided)),
    D('fibula', 'Fibula', 'skeleton', 'Lower limb', 'A slender bone on the outer side of the lower leg that ends in the outer ankle bump.', 'Anchors muscles and steadies the ankle; carries little weight.', Object.assign({ color: BONE }, sided)),
    D('foot', 'Foot bones', 'skeleton', 'Lower limb', 'Twenty-six bones: seven tarsals (heel and midfoot), five metatarsals and fourteen phalanges.', 'Forms the arches that absorb shock and act as a lever to push off when walking.', Object.assign({ color: BONE }, sided)),

    // ===================================================== MUSCLES (superficial)
    D('masseter', 'Masseter', 'muscles', 'Head', 'A thick quadrangular muscle from the cheekbone to the angle of the lower jaw.', 'Closes the jaw: the strongest muscle for its size, used to bite and chew.', Object.assign({ color: MUS }, sided)),
    D('scm', 'Sternocleidomastoid', 'muscles', 'Neck', 'A strap-like muscle running from the bone behind the ear to the sternum and collarbone.', 'Turns the head to the opposite side and tilts it; both together flex the neck.', Object.assign({ color: MUS, label: 1 }, sided)),
    D('trapezius', 'Trapezius', 'muscles', 'Back', 'A large diamond-shaped muscle spanning the skull base, neck and mid-back to the shoulder blade.', 'Raises, lowers and pulls back the scapula and helps tilt and extend the head.', Object.assign({ color: MUS, label: 2 }, sided)),
    D('latissimus', 'Latissimus dorsi', 'muscles', 'Back', 'The broadest muscle of the back, fanning from the lower spine and pelvis to the upper arm.', 'Pulls the raised arm down and back, as in climbing, rowing or swimming.', Object.assign({ color: MUS, label: 1 }, sided)),
    D('pectoralis', 'Pectoralis major', 'muscles', 'Thorax', 'A fan-shaped chest muscle with clavicular and sternal heads that converge on the upper arm.', 'Flexes, adducts and rotates the arm inward; used to push and throw.', Object.assign({ color: MUS, label: 3 }, sided)),
    D('serratus', 'Serratus anterior', 'muscles', 'Thorax', 'Finger-like slips from the upper eight ribs to the inner edge of the shoulder blade.', 'Holds the scapula against the ribcage and rotates it upward when you reach or punch.', Object.assign({ color: MUS }, sided)),
    D('rectus', 'Rectus abdominis', 'muscles', 'Abdomen', 'The paired "six-pack" muscle running from the ribs to the pubis, divided by tendinous intersections.', 'Flexes the trunk and compresses the abdomen; stabilises the pelvis.', Object.assign({ color: MUS, label: 2 }, sided)),
    D('oblique', 'External oblique', 'muscles', 'Abdomen', 'The largest and outermost of the flank muscles; its fibres run down and inward like hands in pockets.', 'Rotates and bends the trunk and compresses the abdominal contents.', Object.assign({ color: MUS }, sided)),
    D('deltoid', 'Deltoid', 'muscles', 'Upper limb', 'The rounded cap of the shoulder with anterior, lateral and posterior heads.', 'Raises the arm forward, sideways and backward.', Object.assign({ color: MUS, label: 3 }, sided)),
    D('biceps', 'Biceps brachii', 'muscles', 'Upper limb', 'The two-headed muscle on the front of the upper arm, with a strong tendon to the radius.', 'Bends the elbow and turns the forearm so the palm faces up.', Object.assign({ color: MUS, label: 3 }, sided)),
    D('triceps', 'Triceps brachii', 'muscles', 'Upper limb', 'The three-headed muscle on the back of the upper arm, attaching to the olecranon.', 'The main muscle that straightens the elbow, as in pushing.', Object.assign({ color: MUS }, sided)),
    D('flexors', 'Forearm flexors', 'muscles', 'Upper limb', 'A group on the inner forearm whose tendons cross the wrist to the palm and fingers.', 'Flex the wrist and fingers and give grip strength.', Object.assign({ color: MUS }, sided)),
    D('extensors', 'Forearm extensors', 'muscles', 'Upper limb', 'A group on the outer forearm whose long tendons run over the back of the hand.', 'Extend the wrist and fingers, opening the hand.', Object.assign({ color: MUS }, sided)),
    D('gluteus_max', 'Gluteus maximus', 'muscles', 'Pelvis', 'The largest and most superficial muscle of the buttock.', 'Extends and rotates the hip outward: powers climbing stairs, running and standing up.', Object.assign({ color: MUS, label: 2 }, sided)),
    D('quadriceps', 'Quadriceps femoris', 'muscles', 'Lower limb', 'Four heads on the front of the thigh: rectus femoris and the three vasti, joined in the patellar tendon.', 'Straightens the knee; the rectus femoris also flexes the hip.', Object.assign({ color: MUS, label: 3 }, sided)),
    D('sartorius', 'Sartorius', 'muscles', 'Lower limb', 'The longest muscle in the body, a thin strap crossing the thigh from the hip bone to the inner knee.', 'Flexes and rotates the hip and bends the knee, as in sitting cross-legged.', Object.assign({ color: MUS }, sided)),
    D('adductors', 'Adductor group', 'muscles', 'Lower limb', 'Gracilis, adductor longus, brevis and magnus on the inner thigh.', 'Pull the thigh toward the midline and steady the pelvis.', Object.assign({ color: MUS }, sided)),
    D('hamstrings', 'Hamstrings', 'muscles', 'Lower limb', 'Biceps femoris, semitendinosus and semimembranosus on the back of the thigh.', 'Bend the knee and extend the hip; brake the leg when running.', Object.assign({ color: MUS }, sided)),
    D('gastrocnemius', 'Gastrocnemius', 'muscles', 'Lower limb', 'The superficial two-headed calf muscle, joined to the heel by the Achilles tendon.', 'Points the foot down to push off when walking, running and jumping.', Object.assign({ color: MUS, label: 2 }, sided)),
    D('tibialis', 'Tibialis anterior', 'muscles', 'Lower limb', 'A muscle along the front of the shin whose tendon crosses the ankle to the inner foot.', 'Lifts the front of the foot so the toes clear the ground; helps arch the foot.', Object.assign({ color: MUS }, sided)),

    // ===================================================== MUSCLES (deep)
    D('pectoralis_minor', 'Pectoralis minor', 'muscles', 'Thorax', 'A thin triangular muscle beneath pectoralis major, from the third to fifth ribs to the coracoid process.', 'Pulls the shoulder blade forward and down; lifts ribs when breathing hard.', Object.assign({ color: MUSD, layer: 'deep' }, sided)),
    D('intercostal', 'Intercostal muscles', 'muscles', 'Thorax', 'Layers of short muscle fibres filling the spaces between adjacent ribs.', 'Raise and lower the ribs during breathing and brace the chest wall.', Object.assign({ color: MUSD, layer: 'deep' }, sided)),
    D('diaphragm', 'Diaphragm', 'muscles', 'Thorax', 'A dome-shaped sheet of muscle and tendon separating the chest from the abdomen.', 'The main muscle of breathing: it flattens to draw air into the lungs.', { color: '#a64545', layer: 'deep', label: 2 }),
    D('rotator', 'Rotator cuff', 'muscles', 'Upper limb', 'Supraspinatus, infraspinatus, teres minor and subscapularis around the shoulder joint.', 'Hold the head of the humerus in its socket and rotate the arm.', Object.assign({ color: MUSD, layer: 'deep' }, sided)),
    D('brachialis', 'Brachialis', 'muscles', 'Upper limb', 'A deep muscle beneath the biceps on the lower front of the humerus.', 'The main workhorse that bends the elbow in every position of the forearm.', Object.assign({ color: MUSD, layer: 'deep' }, sided)),
    D('erector', 'Erector spinae', 'muscles', 'Back', 'Three columns (iliocostalis, longissimus, spinalis) running along both sides of the spine.', 'Straighten the spine and keep the trunk upright; bend it sideways when one side acts.', Object.assign({ color: MUSD, layer: 'deep' }, sided)),
    D('psoas', 'Psoas major', 'muscles', 'Abdomen', 'A long muscle from the lumbar spine, passing the pelvic brim to the top of the femur.', 'The strongest hip flexor: lifts the thigh and bends the trunk forward.', Object.assign({ color: MUSD, layer: 'deep' }, sided)),
    D('gluteus_med', 'Gluteus medius', 'muscles', 'Pelvis', 'A fan-shaped muscle on the outer surface of the ilium, under gluteus maximus.', 'Abducts the thigh and keeps the pelvis level when you stand on one leg.', Object.assign({ color: MUSD, layer: 'deep' }, sided)),
    D('soleus', 'Soleus', 'muscles', 'Lower limb', 'A flat deep calf muscle beneath gastrocnemius, sharing the Achilles tendon.', 'Points the foot down and holds the body upright against gravity when standing.', Object.assign({ color: MUSD, layer: 'deep' }, sided)),

    // ===================================================== ORGANS
    D('eye', 'Eye', 'organs', 'Head', 'A fluid-filled sphere about 2.4 cm across with a clear cornea in front, an iris and pupil, and a lens behind.', 'Focuses light on the retina, which turns it into nerve signals for the brain.', Object.assign({ color: '#f4eee8', label: 1 }, sided)),
    D('thyroid', 'Thyroid gland', 'organs', 'Neck', 'A butterfly-shaped gland wrapped around the front of the windpipe, below the larynx.', 'Makes thyroid hormones that set the speed of the body\'s metabolism.', { color: '#b8645c' }),
    D('larynx', 'Larynx', 'organs', 'Neck', 'The voice box: a cartilage skeleton including the thyroid cartilage ("Adam\'s apple") that holds the vocal folds.', 'Produces voice and closes off the airway when swallowing.', { color: '#d4dde0' }),
    D('trachea', 'Trachea and bronchi', 'organs', 'Thorax', 'The windpipe, a tube reinforced by C-shaped cartilage rings that divides into the two main bronchi.', 'Carries air between the larynx and the lungs and warms and filters it.', { color: '#c4d0da', label: 2 }),
    D('esophagus', 'Esophagus', 'organs', 'Thorax', 'A muscular tube about 25 cm long behind the trachea that passes through the diaphragm to the stomach.', 'Moves swallowed food to the stomach by waves of contraction (peristalsis).', { color: '#d99a8c' }),
    D('lung', 'Lung', 'organs', 'Thorax', 'A cone-shaped, spongy organ. The right lung has three lobes, the left has two and a notch for the heart.', 'Exchanges gas: oxygen enters the blood and carbon dioxide leaves through some 300 million alveoli.', Object.assign({ color: '#ecaab0', label: 3 }, sided)),
    D('liver', 'Liver', 'organs', 'Abdomen', 'The largest internal organ, under the diaphragm on the right side, with a large right lobe and smaller left lobe.', 'Filters blood, makes bile, stores glycogen and builds many blood proteins; processes drugs and toxins.', { color: '#8d3a2e', label: 3 }),
    D('gallbladder', 'Gallbladder', 'organs', 'Abdomen', 'A pear-shaped sac tucked under the liver.', 'Stores and concentrates bile and releases it into the small intestine to digest fat.', { color: '#436f4e' }),
    D('stomach', 'Stomach', 'organs', 'Abdomen', 'A J-shaped muscular sac below the diaphragm with a fundus, body and pylorus.', 'Churns food with acid and enzymes to start protein digestion and passes it on in small amounts.', { color: '#e2917e', label: 3 }),
    D('spleen', 'Spleen', 'organs', 'Abdomen', 'A fist-sized purple organ high on the left side behind the stomach.', 'Filters old red blood cells and stores platelets; part of the immune system.', { color: '#7a2e4d' }),
    D('pancreas', 'Pancreas', 'organs', 'Abdomen', 'A long, lumpy gland lying behind the stomach with a head, body and tail.', 'Releases digestive enzymes into the small intestine and insulin and glucagon into the blood.', { color: '#e7c47c' }),
    D('kidney', 'Kidney', 'organs', 'Abdomen', 'A bean-shaped organ against the back wall of the abdomen, protected by the lower ribs.', 'Filters about 180 litres of blood a day to make urine and balance water, salts and blood pressure.', Object.assign({ color: '#a1463a', label: 2 }, sided)),
    D('adrenal', 'Adrenal gland', 'organs', 'Abdomen', 'A small cap-shaped gland that sits on top of each kidney.', 'Releases adrenaline, cortisol and aldosterone to manage stress, metabolism and salt balance.', Object.assign({ color: '#d9a85a' }, sided)),
    D('smallint', 'Small intestine', 'organs', 'Abdomen', 'About 6 m of coiled tube: duodenum, jejunum and ileum, lined with folds and villi.', 'Completes digestion and absorbs nearly all nutrients into the blood.', { color: '#e9a894', label: 3 }),
    D('largeint', 'Large intestine', 'organs', 'Abdomen', 'The cecum, ascending, transverse, descending and sigmoid colon and rectum, framing the small intestine.', 'Absorbs water and salts and forms and stores feces.', { color: '#cc806a', label: 2 }),
    D('ureter', 'Ureter', 'organs', 'Abdomen', 'A thin muscular tube about 25 cm long running from each kidney down to the bladder.', 'Carries urine to the bladder with waves of contraction.', Object.assign({ color: '#f1e3a2' }, sided)),
    D('bladder', 'Urinary bladder', 'organs', 'Pelvis', 'A stretchy muscular sac in the pelvis, behind the pubic bones.', 'Stores urine and empties it through the urethra.', { color: '#e6c677', label: 1 }),

    // ===================================================== CIRCULATORY
    D('heart', 'Heart', 'circulatory', 'Thorax', 'A four-chambered muscular pump about the size of a fist, tilted to the left behind the sternum, with coronary vessels on its surface.', 'Beats about 100,000 times a day: the right side pumps blood to the lungs, the left side to the whole body.', { color: '#ffffff', label: 3 }),
    D('pulmonary', 'Pulmonary vessels', 'circulatory', 'Thorax', 'The pulmonary trunk and its branches (blue-violet) and four pulmonary veins (red).', 'Arteries take oxygen-poor blood to the lungs; veins bring freshly oxygenated blood back to the left atrium.', { color: '#6f59c8' }),
    D('aorta', 'Aorta', 'circulatory', 'Thorax', 'The largest artery. It rises from the left ventricle, arches over the heart and runs down in front of the spine to the iliac arteries.', 'Distributes oxygen-rich blood to almost every organ via its branches.', { color: '#d12f34', label: 3 }),
    D('svc', 'Superior vena cava', 'circulatory', 'Thorax', 'A large vein formed by the union of the two brachiocephalic veins, entering the right atrium from above.', 'Returns blood from the head, neck, arms and upper chest to the heart.', { color: '#3b5bc9' }),
    D('ivc', 'Inferior vena cava', 'circulatory', 'Abdomen', 'The largest vein, running up the right side of the spine, receiving the renal and iliac veins.', 'Returns blood from the legs, pelvis and abdomen to the right atrium.', { color: '#3b5bc9', label: 1 }),
    D('carotid', 'Carotid artery', 'circulatory', 'Neck', 'The common carotid divides in the neck into an internal branch for the brain and an external branch for the face.', 'Supplies oxygenated blood to the head and brain; its pulse can be felt beside the windpipe.', Object.assign({ color: '#d12f34' }, sided)),
    D('jugular', 'Jugular vein', 'circulatory', 'Neck', 'The large vein on each side of the neck, running alongside the carotid artery.', 'Drains blood from the brain, face and neck back to the heart.', Object.assign({ color: '#3b5bc9' }, sided)),
    D('brachial', 'Brachial and forearm arteries', 'circulatory', 'Upper limb', 'The subclavian artery continues down the arm as the brachial artery, splitting at the elbow into the radial and ulnar arteries.', 'Supplies the arm and hand; the usual site for taking blood pressure.', Object.assign({ color: '#d12f34' }, sided)),
    D('femoral_a', 'Femoral artery', 'circulatory', 'Lower limb', 'The continuation of the external iliac artery through the thigh; behind the knee it becomes the popliteal artery and divides into the tibial arteries.', 'Main blood supply to the leg and foot.', Object.assign({ color: '#d12f34', label: 1 }, sided)),
    D('femoral_v', 'Femoral vein', 'circulatory', 'Lower limb', 'The deep vein of the thigh running alongside the femoral artery.', 'Carries blood from the leg back up toward the heart; calf muscles help pump it.', Object.assign({ color: '#3b5bc9' }, sided)),
    D('renal_a', 'Renal artery', 'circulatory', 'Abdomen', 'A short, wide branch of the abdominal aorta to each kidney.', 'Delivers about a fifth of the heart\'s output to the kidneys for filtering.', Object.assign({ color: '#d12f34' }, sided)),
    D('renal_v', 'Renal vein', 'circulatory', 'Abdomen', 'The vein leaving each kidney and draining into the inferior vena cava.', 'Returns filtered blood from the kidney.', Object.assign({ color: '#3b5bc9' }, sided)),

    // ===================================================== NERVOUS
    D('lobe_frontal', 'Frontal lobe', 'nervous', 'Head', 'The largest lobe, at the front of each cerebral hemisphere, ending at the central sulcus.', 'Planning, decision-making, personality, speech production and voluntary movement.', Object.assign({ color: '#ffffff', label: 3 }, sided)),
    D('lobe_parietal', 'Parietal lobe', 'nervous', 'Head', 'The lobe on the upper back of each hemisphere, behind the central sulcus.', 'Processes touch, pain, temperature and spatial awareness.', Object.assign({ color: '#ffffff', label: 2 }, sided)),
    D('lobe_temporal', 'Temporal lobe', 'nervous', 'Head', 'The lobe below the lateral fissure on each side, near the ear.', 'Hearing, language comprehension and memory formation.', Object.assign({ color: '#ffffff', label: 2 }, sided)),
    D('lobe_occipital', 'Occipital lobe', 'nervous', 'Head', 'The smallest lobe, at the back of each hemisphere.', 'Processes vision: colour, shape and movement.', Object.assign({ color: '#ffffff', label: 1 }, sided)),
    D('cerebellum', 'Cerebellum', 'nervous', 'Head', 'The "little brain" below the occipital lobes, with finely folded surface.', 'Coordinates balance, posture and smooth, accurate movement.', { color: '#ffffff', label: 2 }),
    D('brainstem', 'Brainstem', 'nervous', 'Head', 'Midbrain, pons and medulla oblongata joining the brain to the spinal cord.', 'Controls breathing, heart rate, swallowing and wakefulness; relays all signals between brain and body.', { color: '#ffffff' }),
    D('cord', 'Spinal cord', 'nervous', 'Spine', 'About 45 cm of nerve tissue inside the vertebral canal, ending at L1-L2 in a fan of nerve roots (cauda equina).', 'Carries signals between the brain and the body and handles simple reflexes.', { color: '#f3e7a6', label: 3 }),
    D('vagus', 'Vagus nerve', 'nervous', 'Neck', 'The tenth cranial nerve, running from the brainstem through the neck and chest to the abdomen.', 'Slows the heart, stimulates digestion and carries sensation from many organs.', Object.assign({ color: '#f1cf55' }, sided)),
    D('plexus', 'Brachial plexus', 'nervous', 'Upper limb', 'A network of nerve roots from the spinal cord (C5-T1) that merges and splits above the collarbone and in the armpit.', 'Supplies movement and sensation to the shoulder, arm and hand.', Object.assign({ color: '#f1cf55', label: 2 }, sided)),
    D('median', 'Median nerve', 'nervous', 'Upper limb', 'Runs down the middle of the arm and through the carpal tunnel to the hand.', 'Controls most forearm flexors and the thumb muscles; gives feeling to the thumb, index and middle fingers.', Object.assign({ color: '#f1cf55' }, sided)),
    D('ulnar', 'Ulnar nerve', 'nervous', 'Upper limb', 'Passes behind the medial epicondyle (the "funny bone") to the hand.', 'Moves the small muscles of the hand and feels the little and ring fingers.', Object.assign({ color: '#f1cf55' }, sided)),
    D('radial', 'Radial nerve', 'nervous', 'Upper limb', 'Winds around the back of the humerus and down the outer forearm.', 'Extends the elbow, wrist and fingers and feels the back of the hand.', Object.assign({ color: '#f1cf55' }, sided)),
    D('sciatic', 'Sciatic nerve', 'nervous', 'Lower limb', 'The longest and thickest nerve: runs from the sacral plexus through the buttock and splits above the knee into the tibial and common fibular nerves.', 'Moves the hamstrings and all muscles below the knee and gives feeling to most of the leg and foot.', Object.assign({ color: '#f1cf55', label: 2 }, sided)),
    D('femoral_n', 'Femoral nerve', 'nervous', 'Lower limb', 'The largest branch of the lumbar plexus, passing under the inguinal ligament into the front of the thigh.', 'Powers the quadriceps and gives feeling to the front of the thigh and inner leg.', Object.assign({ color: '#f1cf55' }, sided)),
    D('optic', 'Optic nerve', 'nervous', 'Head', 'A bundle of about a million fibres from the retina back toward the brain, meeting its partner at the optic chiasm.', 'Carries visual information from the eye to the brain.', Object.assign({ color: '#f1cf55' }, sided))
  ];

  // View presets: which systems are on, and per-system opacity (ghosting)
  A.PRESETS = [
    { id: 'all',     label: 'Everything', key: '1', systems: { skeleton: 1, muscles: 0, organs: 1, circulatory: 1, nervous: 1 } },
    { id: 'skeleton', label: 'Skeleton',  key: '2', systems: { skeleton: 1 } },
    { id: 'muscles', label: 'Muscles',    key: '3', systems: { muscles: 1, skeleton: 0.25 }, layers: ['superficial'] },
    { id: 'deep',    label: 'Deep muscles', key: '4', systems: { muscles: 1, skeleton: 0.5 }, layers: ['deep'] },
    { id: 'organs',  label: 'Organs',     key: '5', systems: { organs: 1, skeleton: 0.2 } },
    { id: 'circ',    label: 'Circulatory', key: '6', systems: { circulatory: 1, skeleton: 0.2, organs: 0.15 } },
    { id: 'nerve',   label: 'Nervous',    key: '7', systems: { nervous: 1, skeleton: 0.2 } }
  ];
})(window.ANATOMY);
